#include <iostream>
#include <filesystem>
#include <fstream>
#include <string>
#include <cstdlib>
#include <stdexcept>
#include <unistd.h>
#include <csignal>
#include <unordered_map>
#include <functional>
#include <conio.h>
#include <thread>
#include "json.hpp"
#include "rw.hpp"
#include "pac.hpp"
#include "usrAuth.hpp"
#include "mdr.hpp"